In [247]:
# Create timestamp
import datetime
print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2025-08-19 17:41:13.258029


### Introduction to Tensors

In [248]:
# Import TensorFlow
import tensorflow as tf 
print(tf.__version__) # find the version number 

2.20.0


### Creating tensors with `tf.constant()`

In [256]:
# Create a scalar (rank 0 tensor)

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [257]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim


0

In [258]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [259]:
# check the number of dimensions of our vector tensor
vector.ndim # this has one dimension. because it has one [] 

1

In [260]:
# create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [265]:
matrix.ndim 

2

by default, TensorFlow creates tensord with either an int32 or float32 datatype.

this is known as 32-bit precision(the higher the number, the more precise the number, the more space it takes up on your computer)

In [266]:
# create another matrix and define the datatype

another_matrix = tf.constant([[10.0, 7.0], [3.0, 2.0], [8.0, 9.0]], dtype=tf.float16) # specify the datatype with `dtype`
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [267]:
#even thouh another_matrix contains more numbers, its dimensions stay the same
another_matrix.ndim

2