In [1]:
# Create timestamp
import datetime
print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2025-08-20 17:39:54.548982


### Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf 
print(tf.__version__) # find the version number 

2.20.0


### Creating tensors with `tf.constant()`

In [3]:
# Create a scalar (rank 0 tensor)

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim


0

In [5]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the number of dimensions of our vector tensor
vector.ndim # this has one dimension. because it has one [] 

1

In [7]:
# create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim 

2

by default, TensorFlow creates tensord with either an int32 or float32 datatype.

this is known as 32-bit precision(the higher the number, the more precise the number, the more space it takes up on your computer)

In [9]:
# create another matrix and define the datatype

another_matrix = tf.constant([[10.0, 7.0], [3.0, 2.0], [8.0, 9.0]], dtype=tf.float16) # specify the datatype with `dtype`
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
#even thouh another_matrix contains more numbers, its dimensions stay the same
another_matrix.ndim

2

In [11]:
# how about a tensor? (more than 2 dimension, although , all of the above items are also technically tensors)

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3


    scalar: a single number.
    vector: a number with direction (e.g. wind speed with direction).
    matrix: a 2-dimensional array of numbers.
    tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).


![alt text](<screeenshots/Screenshot 2025-08-20 161538.png>)

## Creating Tensors with tf.Variable()

you can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using `tf.Variable()`

the difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are mutable(can be changed).

In [13]:
# create the same tensor with tf.Variable() and tf.constant()

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# will error (requires the .assign() method)
# changeable_tensor[0] = 7
# changeable_tensor

# TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
changeable_tensor[0].assign(7)  
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# will error (can't change a constant tensor)
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

which one should you use? `tf.constant()` or `tf.Variable()`

it will depend on what your problem requires. However, most of the time, TensorFlow will automatically choosr for you (when loading data or modelling data).

## Creating random tensors

random tensors are tensors of some abitary size which contain random numbers.

why would you want to crate random tensors?

this is what neural network use to unitialize their weights (patterns) that they're trying to learn in the data.

for example, the process of a neural network learining often involes taking a random n-dimensional array of numbers and tefining them until they represent some kind of pattern (a compressed way to represent the original data).

we can create random tensors by using the `tf.random.Generator` class.

In [17]:
# create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution

random_2 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))

# Are they qual?

random_1 , random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# shuffle a tensor (valueable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# get different result each time

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [19]:
# shuffle in the same order every time using the seed parameter (won't actually be the same)

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Wait... why didn't the numbers come out the same?

It's due to rule #4 of the `tf.random.set_seed()` documentation.

`"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."`

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

In [20]:
# shuffle in the same order every time

# set the global random seed
tf.random.set_seed(42)

# set the oprtaional random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

## Other ways to make tensors

In [22]:
# make a tensor of all ones
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [23]:
# make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

you can also turn NumPy arrays into tensors.

Remember, the main difference between tensors and NumPy arrays is the tensors can be run on GPUs.

In [24]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25

A = tf.constant(numpy_A, shape=[2, 4, 3]) # note: the shape total (2*4*3) has match the number of elements in the array

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Getting information from tensors (shape, rank, size)


    Shape: The length (number of elements) of each of the dimensions of a tensor.
    Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
    Axis or Dimension: A particular dimension of a tensor.
    Size: The total number of items in the tensor.


In [25]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor) # shape, number of dimensions, total number of elements

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


You can also index tensors just like Python lists

In [28]:
# get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2] # get the first 2 items of each dimension

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# get the dimensions from each index except for the final one
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [30]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3,4]])

# get the last item of each dimension
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

you can also add dimensions to your tensor whilst keeping the same information presrnt using `tf.newaxis`

In [31]:
# add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2,2), shape (2,2,1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

you can achieve the same using `tf.expand_dims()`

In [36]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipulating tensors (tensor operations)

Finding patterns in tensors (numberical representation of data) requires manipulating them

again, when building models in TensorFlow, much of this pattern discovery is done for you.

## Basic operations

you can perform many of the basic mathematical operations directly on tensors using Pyton operators such as, +,-.*.

In [37]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

since we used `tf.constant()` , the original tensor is unchanged(the addition get done on a copy)

In [38]:
# original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

other operation also work

In [39]:
# multiplication (known as element-wise multiplication)

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [40]:
# substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

you can also use the equivalant TensorFlow function. using the TensorFlow function(where possible) has the advantage of beign sped up later down the line when running as part of a TensorFlow graph.